export const companies = [
  {
    ticker: "4478",
    name: "freee",
    sector: "クラウド会計",
    metrics: {
      revenueGrowth: 28,
      grossProfitGrowth: 31,
      operatingMargin: -8,
      ebitdaMargin: -3,
      ocfMargin: 4,
      ruleOf40: 25,
      operatingCashFlows: [-1200, -800, 300],
      operatingIncomes: [-2300, -1800, -900],
      cash: 42000,
      monthlyCashBurn: 0,
      currentLiabilities: 21000,
      equityRatio: 58,
      hasMsWarrant: false,
      equityFinancingCountLast3Years: 1,
      auditorChanged: false,
      goingConcernNote: false,
      currentRatioTrend: "stable" as const,
      warrantTrend: "none" as const,
      cbTrend: "none" as const,
    },
  },
  {
    ticker: "4475",
    name: "HENNGE",
    sector: "セキュリティSaaS",
    metrics: {
      revenueGrowth: 22,
      grossProfitGrowth: 26,
      operatingMargin: 12,
      ebitdaMargin: 18,
      ocfMargin: 16,
      ruleOf40: 40,
      operatingCashFlows: [1200, 1800, 2600],
      operatingIncomes: [900, 1400, 2100],
      cash: 18000,
      monthlyCashBurn: 0,
      currentLiabilities: 7000,
      equityRatio: 72,
      hasMsWarrant: false,
      equityFinancingCountLast3Years: 0,
      auditorChanged: false,
      goingConcernNote: false,
      currentRatioTrend: "improving" as const,
      warrantTrend: "none" as const,
      cbTrend: "none" as const,
    },
  },
  {
    ticker: "4419",
    name: "Finatext",
    sector: "Fintech",
    metrics: {
      revenueGrowth: 35,
      grossProfitGrowth: 30,
      operatingMargin: 5,
      ebitdaMargin: 9,
      ocfMargin: 2,
      ruleOf40: 44,
      operatingCashFlows: [-900, -400, 100],
      operatingIncomes: [-700, -300, 200],
      cash: 12000,
      monthlyCashBurn: 1000,
      currentLiabilities: 9000,
      equityRatio: 46,
      hasMsWarrant: false,
      equityFinancingCountLast3Years: 1,
      auditorChanged: false,
      goingConcernNote: false,
      currentRatioTrend: "stable" as const,
      warrantTrend: "stable" as const,
      cbTrend: "none" as const,
    },
  },
];

export function findCompanyByTicker(ticker: string) {
  return companies.find((company) => company.ticker === ticker);
}